### ISSUE TITLE
No module named thready

### ISSUE THREAD

**Issue by jorgejaque** [mdsecactivebreach/LinkedInt#2]
Any help with this error will be appreciated: 
Running on Python 2.7.13

Traceback (most recent call last):
  File "LinkedInt.py", line 27, in <module>
    from thready import threaded
ImportError: No module named thready

**Comment by vysec** [comment]
Pop install thready

**Comment by vysec** [comment]
Pip rather

**Comment by jorgejaque** [comment]
It should be:
pip2.7 install thready

Thanks!
